Repository openfun/learninglocker-docker, pull requests merged in 2019-06, with the labels that each got.

#25 Automate new releases image publication
  README.md
  bin/release
Labels: feature, needs review

#27 🔖(learninglocker) bump version to v3.15.1
  .circleci/releases.sh
Labels: FUN, needs review

#28 🔖(learninglocker) bump version to v3.15.2
  .circleci/releases.sh
Labels: FUN

#30 🔖(xapi-service) bump version to v2.5.4 and v2.5.5
  .circleci/releases.sh
Labels: FUN

#32 🐛(utils) ignore grep error if targeted commit does not exists
  bin/release
Labels: bug

#31 Prepare releases v3.15.4, v3.15.5 and v3.15.6 for LL
  .circleci/releases.sh
Labels: FUN

#33 releases v3.15.7, v3.15.8 of LL and v2.5.6 of xapi-service
  .circleci/releases.sh
Labels: FUN
